#!/usr/bin/env php
<?php
namespace Brain\Games\Cli;
require_once __DIR__ . '/../../vendor/autoload.php';

echo "Welcome to the Brain Games!", PHP_EOL;
$name = in("May I have your name? ");
echo "Hello, ", $name, "!", PHP_EOL;
echo 'Answer "yes" if given number is prime. Otherwise answer "no".', PHP_EOL;
//$flag = false;

for ($i = 1; $i <= 3; $i++)
{
    $number = rand(1, 100);
    echo "Question: ", $number, PHP_EOL;
    $answer = in("Your answer: ");
    if ($answer != 'yes' && $answer != 'no')
    {
        echo "'", $answer, "' is wrong answer ;(. Correct answer is 'yes' or 'no'", PHP_EOL, "Let's try again, ", $name, "!", PHP_EOL;
 //       $flag = false;
        break;
    }
    elseif ($answer === 'yes' && prime($number))
    {
        echo "Correct! ", PHP_EOL;
//        $flag = true;
    }
    elseif ($answer === 'no' && !prime($number))
    {
        echo "Correct! ", PHP_EOL;
//        $flag = true;
    }
    else
    {
        echo "Let's try again, ", $name, "!", PHP_EOL;
 //       $flag = false;
        break;
    }
}
//if ($flag === true)
//{
    echo "Congratulations, ", $name. "!", PHP_EOL;
//}
